NumPy Basics

In [2]:
import numpy as np
data=[1,2,3,4,5,6,7]
ar=np.array(data,np.float64)
ar

array([1., 2., 3., 4., 5., 6., 7.])

In [8]:
arrc = np.array([[1, 2], [3, 4]], dtype=complex)
arrc

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [ ]:
# list to 2d array
arr1=np.array([[4.5, 6.3,7],[8.9,5.6,4.2]])
arr2=arr1[:]
arr2

In [ ]:
#conversion back to list
arr1.tolist()
arr1

In [ ]:
# common methods
np.zeros(10)
np.zeros((3, 6))
np.ones(10)
np.arange(1,10,2)
np.linspace(0, 10, 50) # 0 to 10 (inclusive) with 50 points
np.logspace(0, 3, 4) # 10^0 to 10^3 (inclusive) with 4 points

In [ ]:
# astype
int_array=np.arange(10)
float_array=int_array.astype(float)
float_array

In [ ]:
arr1.dtype 
arr2.ndim # 2
arr2.shape # (2, 4) - axis 0 is rows, axis 1 is columns
arr2.size # 8 - total number of elements
len(arr2) # 2 - size of first dimension (aka axis)

In [ ]:
#Add an axis
# 1D to column vector
a = np.array([0, 1,2,3,4])
a_col = a[:, np.newaxis]
print(a_col)
a_col.shape
a_row=a[np.newaxis,:]
print(a_row,a_row.shape)

In [19]:
# Flatten: always returns a flat copy of the original array
arr5=np.arange(10).reshape(2,5)
arr_flt = arr5.flatten()
arr_flt[0] = 33
print(arr_flt)
print(arr5)

[33  1  2  3  4  5  6  7  8  9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [21]:
arr5.ravel()  # returns the modified array, flattened and unchanged in original way, only view

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
#Returns the indices of the maximum values along an axis.
x = np.array([[4,2,3], [1,0,3]])
index_array = np.argmax(x, axis=1)
index_array

array([0, 2], dtype=int64)

In [ ]:
# argmin - index of min value
# argnanmax - max index ignoring nan values
# argwhere

In [31]:
#np.where(condition, [x, y, ]/)
#Return elements chosen from x or y depending on condition.
a = np.arange(10)
np.where(a < 5, a, 10*a)

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

In [24]:
a = np.array([[1, 2],[ 3, 4]])
b = np.array([[5, 6],[7, 8]])
np.concatenate((a,b),axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [4]:
a=np.random.randint(1,10,6).reshape(2,3)
b=np.floor(10*np.random.randn(2,3))
c=np.vstack((a,b))
np.hstack((b,a))

array([[ 4., -8., -1.,  6.,  9.,  9.],
       [-4., -4., -7.,  7.,  9.,  3.]])

In [8]:
# splitting hsplit,vsplit
np.vsplit(c,2)

[array([[6., 9., 9.],
        [7., 9., 3.]]),
 array([[ 4., -8., -1.],
        [-4., -4., -7.]])]

#### Slicing and Indexing

In [ ]:
arr = np.arange(10, dtype=float).reshape((2, 5))
arr[0] # 0th element (slices like a list)
arr[0, 3] # row 0, column 3: returns 4
arr[0][3] # alternative syntax

In [ ]:
arr[0, :] # row 0: returns 1d array ([1, 2, 3, 4])
arr[:, 0] # column 0: returns 1d array ([1, 5])
arr[:, :2] # columns strictly before index 2 (2 first columns)
arr[:, 2:] # columns after index 2 included
ab = arr[:, 1:4] # columns between index 1 (included) and 4 (excluded)
print(ab)
ab[[0,1]]

In [ ]:
#reverse order
print(arr[0, ::-1])

In [ ]:
#Boolean arrays indexing
arr2 = arr[arr > 5] # return a copy
print(arr2)
arr2[0] = 44
print(arr2)
print(arr)

In [10]:
rg = np.random.default_rng(1)  # create instance of default random number generator
a = np.ones((4, 3), dtype=int)
b = rg.random((4, 3))
a *= 3
b += a
b

array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645],
       [3.82770259, 3.40919914, 3.54959369],
       [3.02755911, 3.75351311, 3.53814331]])

In [ ]:
np.random.default_rng

In [ ]:
names=np.array(['Raj','Sam','Ram','Sam','Mick','Lucky','Sam'])
data=np.random.randn(7,4)  #random function
data

In [ ]:
names

In [ ]:
np.unique(names)

In [ ]:
names=='Sam'    #boolean 

In [ ]:
data[names=='Sam']

In [ ]:
data[names=='Sam',:2]

In [ ]:
mask=(names=='Sam')&(names!='Raj')
mask

In [ ]:
data[mask]

In [ ]:
data[data<0]=0
data

In [ ]:
data[[2,3]] #row 2,3

In [ ]:
data[0:2,2:]

In [ ]:
data[3,3] #row3,column3

In [ ]:
data1=np.arange(20).reshape(4,5)
data1.T       #Transposes 2D array

In [ ]:
data2=np.arange(27).reshape(3,3,3)

In [ ]:
np.dot(data1.T,data1)  # dot product

In [ ]:
data2

In [ ]:
data2.transpose(1,0,2)   #Transpose multi D

In [ ]:
data2.swapaxes(2,1)     #swaping axes

#### Random

In [179]:
# math and stats
rnd = np.random.randn(4, 2) # random normals in 4x2 array
rnd.mean()
rnd.std()
rnd.argmin() # index of minimum element
rnd.sum()
rnd.sum(axis=0) # sum of columns
rnd.sum(axis=1) # sum of rows
# methods for boolean arrays
(rnd > 0).sum() # counts number of positive values
(rnd > 0).any() # checks if any value is True
(rnd > 0).all() # checks if all values are True
# random numbers
np.random.seed(12234) # Set the seed
np.random.rand(2, 3) # 2 x 3 matrix in [0, 1]
np.random.randn(10) # random normals (mean 0, sd 1)
np.random.randint(0, 2, 10) # 10 randomly picked 0 or 1

array([0, 0, 0, 1, 1, 0, 1, 1, 1, 1])

In [184]:
np.random.seed(12234)

In [7]:
A = np.array([[2, 1],
              [0, 3]])
B = np.array([[5, 0],
              [6, 4]])
A * B     # elementwise product
A @ B     # matrix product
A.dot(B)  # another matrix product

array([[16,  4],
       [18, 12]])

#### Broadcasting

In [4]:
a = np.array([[ 0, 0, 0],     # smaller array is stretched to larger
[10, 10, 10],
[20, 20, 20],
[30, 30, 30]])
b = np.array([0, 1, 2])
print(a + b)

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


##### Unary functions

In [ ]:
data3=np.arange(5)    #ufunc   universal
np.sqrt(data3)         #unary
np.exp(data3)

In [ ]:
x=np.random.randn(5)
y=np.random.randn(5)
np.maximum(x,y)         #binary

In [ ]:
z=np.random.randn(10)*5

In [ ]:
np.modf(z)  #results in fractional and integral part

Unary ufuncs

* abs, fabs - absolute 
* sqrt  - arr ** 0.5 
* square - arr ** 2 
* exp  - exponent 
* log, log10, log2, log1p 
* sign ceil floor rint modf 
* isnan  is NaN (Not a Number)
* isfinite, isinf 
* cos, cosh, sin, sinh, tan, tanh
* arccos, arccosh, arcsin,
* arcsinh, arctan, arctanh
* logical_not - Compute truth value of not x element-wise. Equivalent to -arr

Binary ufuncs

1. add                      - Add corresponding elements in arrays
2. subtract                 - Subtract elements in second array from first array
2. multiply                 - Multiply array elements
2. divide, floor_divide     - Divide or floor divide (truncating the remainder)
2. power                    - Raise elements in first array to powers indicated in second array
2. maximum, fmax            - Element-wise maximum. fmax ignores NaN
2. minimum, fmin            - Element-wise minimum. fmin ignores NaN
2. mod                      - Element-wise modulus (remainder of division)
2. copysign

In [ ]:
points=np.arange(-5,5,1)
xs,ys=np.meshgrid(points,points)
xs

In [ ]:
z=np.sqrt(xs**2+ys**2)
z

In [ ]:
import matplotlib.pyplot as plt
plt.imshow(z, cmap=plt.cm.gray)
plt.colorbar()
plt.title("Image plot of $\sqrt{x^2 + y^2}$ for a grid of values")

In [5]:
arr2=np.random.randn(4,4)    #ternary expression x if condition else y
arr2
result=np.where(arr2>0,1,0)
result

array([[1, 1, 1, 0],
       [1, 0, 0, 0],
       [1, 1, 0, 1],
       [0, 1, 0, 0]])

In [ ]:
arr3=np.random.randn(3,3)
arr3.sum()
arr3.mean()

In [ ]:
np.mean(arr3)

In [ ]:
arr4=np.random.randn(4,5)
print(arr4)
arr4.sort()
arr4


Linear algebra

* diag: Return the diagonal (or off-diagonal) elements of a square matrix as a 1D array, or convert a 1D array into a square matrix with zeros on the off-diagonal
* dot: Matrix multiplication
* trace: Compute the sum of the diagonal elements
* det: Compute the matrix determinant
* eig: Compute the eigenvalues and eigenvectors of a square matrix
* inv: Compute the inverse of a square matrix
* pinv: Compute the Moore-Penrose pseudo-inverse inverse of a square matrix
* qr: Compute the QR decomposition
* svd: Compute the singular value decomposition (SVD)
* solve: Solve the linear system Ax = b for x, where A is a square matrix
* lstsq: Compute the least-squares solution to y = Xb

In [ ]:
arr8=np.array([[1,2],[6,7]])   
a,b=np.linalg.qr(arr8)
b

 Random

* seed: Seed the random number generator 
* permutation: Return a random permutation of a sequence, or return a permuted range
* shuffle: Randomly permute a sequence in place
* rand: Draw samples from a uniform distribution
* randint: Draw random integers from a given low-to-high range
* randn: Draw samples from a normal distribution with mean 0 and standard deviation 1 (MATLAB-like interface)
* binomial: Draw samples from a binomial distribution
* normal: Draw samples from a normal (Gaussian) distribution
* beta: Draw samples from a beta distribution
* chisquare: Draw samples from a chi-square distribution
* gamma: Draw samples from a gamma distribution
* uniform: Draw samples from a uniform [0, 1) distribution